### ISSUE TITLE
Can one contribute to this project from the very start?

### ISSUE THREAD

**Issue by balacode** [campoy/goodgopher#1]
Hi, the idea of "bot" and "github" sounds interesting... even as the project is still a mystery. I'd be happy to contribute in some way (mostly on weekends). I'm new to using github, but have been coding for long. Now mainly using Go since 2016.

**Comment by campoy** [comment]
not yet, sorry

but watch this space, I'll be pushing stuff soon and I'll be happy to have your help then!
